### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by shashankrp** [davidcallanan/os-series#10]
I am facing this issue "docker build buildenv -t myos-buildenv
unable to prepare context: path "buildenv" not found" so any solution
![Screenshot (188)](https://user-images.githubusercontent.com/30649674/108624472-30900680-746b-11eb-8a19-d11f688435d0.png)

**Comment by shashankrp** [comment]
solved the above issue by using "docker build -t myown-env" but now i got a new issue that is 
![image](https://user-images.githubusercontent.com/30649674/108630684-03078500-748c-11eb-94e6-2b50e90e3ae9.png)

**Comment by davidcallanan** [comment]
Latest problem is a duplicate of #5.

**Comment by davidcallanan** [comment]
Shouldn't it be `Dockerfile` not `dockerfile? Try rename the file and then use your initial command.
