### ISSUE TITLE
Issue with Makefile

### ISSUE THREAD

**Issue by SanteriPit** [davidcallanan/os-series#11]
I have an issue with the makefile thing. It always gives me
make: *** No rule to make target 'build-x86_64'.  Stop.
![image](https://user-images.githubusercontent.com/75909696/108632880-cf236400-7479-11eb-9aff-7ed98c5f58ea.png)
Can somebody help me?
Btw I have cloned everything from branch ep1.

**Comment by SanteriPit** [comment]
And I can't use the normal dockerfile launch because it's on my D drive and I cant find the thing to allocate the drive. If somebody helped me with that then that would also help

**Comment by Marcopollom** [comment]
I had a similar issue when I first started. I fixed it on my end by changing the docker run command from `docker run --rm -it -v "$PWD":/root/env myos-buildenv` to `docker run --rm -it -v /path-to-files:/root/env myos-buildenv`. Basically, instead of using the bash command, I hard-typed out the path.

**Comment by chriswkingg** [comment]
Are you starting the container from powershell or cmd? I had to use a different command for powershell: docker run --rm -it -v "${pwd}:/root/env" myos-buildenv

**Comment by SanteriPit** [comment]
Yeah thanks it fixed it. Did the tutorial say that you need to use powershell? Because I totally missed it if it was in the video. First I didn't know why docker run --rm -it -v "${pwd}:/root/env" myos-buildenv didn't work but it was because I used firstos-buildenv as my tag. Mainly because my os was called FirstOS.

**Comment by davidcallanan** [comment]
@SanteriPit There is no requirement to use powershell. However the commands are slightly different depending on what shell you are using.

Here is a list of commands: #38
