### ISSUE TITLE
Qemu unable to boot from CD ROM

### ISSUE THREAD

**Issue by Marcopollom** [davidcallanan/os-series#12]
When I go to run the kernel, Qemu cannot find the file and gives me an error. I've narrowed the issue down to the grub.cfg file, but I cannot seem to find the right path to the kernal.bin file. 

![Screen Shot 2021-02-21 at 6 44 50 PM](https://user-images.githubusercontent.com/58184497/108642755-178c5300-7475-11eb-850a-f38241f08216.png)

edit: The file path in the image was me just testing. I've tried many different paths, including the one provided in `master`

**Comment by davidcallanan** [comment]
Typo `kernal.bin` instead of `kernel.bin`.
