### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by fel1x0u** [davidcallanan/os-series#13]
Has anyone tested on a VM? Maybe that would be better instead of testing on read hardware. Also, how to you build the ISO?

**Comment by fel1x0u** [comment]
well got the iso part done

**Comment by JoaoWalterAmadeu** [comment]
Install QEMU, then use this command to run the ISO:
qemu-system-x86_64.exe -cdrom iso_name.iso  -L "qemu path(probably C:\Program Files\qemu)"

**Comment by aperson1234432107** [comment]
I use virtual box and it works nice, qemu didn't work for me

**Comment by fel1x0u** [comment]
Thanks!
