### ISSUE TITLE
Can you  please show how to link the kernel to a graphical user interface and run apps in the next episode

### ISSUE THREAD

**Issue by SaptakBhoumik** [davidcallanan/os-series#22]

**Comment by sacreative10** [comment]
That might actually take a long time, as GUI, require a lot of driver support and a fully built kernel.

**Comment by SaptakBhoumik** [comment]
It is difficult but very interesting

**Comment by sacreative10** [comment]
I know. But we need a lot of stepping stones first,

**Comment by KingUndeadCodes** [comment]
Good joke!

This is very hard to do.

**Comment by Tarcaxoxide** [comment]
well you could get very basic graphics through the multiboot header that grub provides....
vga/vesa modes.
but so far we only used it to boot the kernel.
