### ISSUE TITLE
x86_64-elf-ld => file format not recognized; treating as linker script

### ISSUE THREAD

**Issue by LePwnerer** [davidcallanan/os-series#24]
make build-x86_64
mkdir -p dist/x86_64 && \
x86_64-elf-ld -n -o dist/x86_64/kernel.bin -T targets/x86_64/linker.ld ./src/impl/x86_64/boot/header.asm ./src/impl/x86_64/boot/main.asm && \
cp dist/x86_64/kernel.bin targets/x86_64/iso/boot/kernel.bin && \
grub-mkrescue /usr/lib/grub/i386-pc -o dist/x86_64/kernel.iso targets/x86_64/iso
x86_64-elf-ld:./src/impl/x86_64/boot/header.asm: file format not recognized; treating as linker script
x86_64-elf-ld:./src/impl/x86_64/boot/header.asm:1: syntax error
Makefile:12: recipe for target 'build-x86_64' failed
make: *** [build-x86_64] Error 1

**Comment by davidcallanan** [comment]
Did you fix this? Was it a mistake in your code?

**Comment by LePwnerer** [comment]
Sorry for the late response. Yeah i fixed it but i can't remember the exact cause. I think it was something along the line that my working directory wasn't accessible and i had to manually change it each time.
