### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by UFifty50** [davidcallanan/os-series#26]
When I try to compile the source it gives me this error:
```
x86_64/print.c:11:1: error: expected ';', identifier or '(' before 'struct'
 struct Char* buffer = (struct Char*) 0xb8000;
```
the command being run:
```
x86_64-elf-gcc -c -std=gnu99 -I include/ -ffreestanding  x86_64/print.c -o build/x86_64/print.o
```
the relevant contents of print.c:
```c
struct Char {
        uint8_t character;
        uint8_t colour;
}

struct Char* buffer = (struct Char*) 0xb8000;

```
my gcc version is a cross-compiled 4.9.0, however i get the exact same error on non-cross-compiled versions 4.7, 7, 9 and 10.
any help would be appreciated!

**Comment by sjx233** [comment]
A semicolon is required after the class specifier, since it is part of a declaration.

```diff
 struct Char {
         uint8_t character;
         uint8_t colour;
-}
+};
 
 struct Char* buffer = (struct Char*) 0xb8000;
```

**Comment by UFifty50** [comment]
Perfect, that worked! thanks :)
