### ISSUE TITLE
No changes being updated

### ISSUE THREAD

**Issue by Roseinabox28** [davidcallanan/os-series#31]
so I've been trying to change the string that we print out at the end of episode 2 but it refuses to change. yes qemu is closed when I build, I don't know what else to do.

**Comment by Roseinabox28** [comment]
![image](https://user-images.githubusercontent.com/48871187/117095924-a0005d00-ad1c-11eb-8f1d-694609d2c390.png)
This is the code
![image](https://user-images.githubusercontent.com/48871187/117095983-ba3a3b00-ad1c-11eb-889f-9c408325df6c.png)
This is what qemu shows

**Comment by Roseinabox28** [comment]
even tried deleting the iso file and rebuilding, no change.

**Comment by Roseinabox28** [comment]
Figured it out. One of my kernel files was misspelled as kernal and wasn't being added to the make.

**Comment by marcioeric** [comment]
Did you close the Qemu and execute again after rebuilding the image?

**Comment by davidcallanan** [comment]
Same typo as #12 .
