### ISSUE TITLE
Issue with booting on real hardware

### ISSUE THREAD

**Issue by AnUnkownSkeleton** [davidcallanan/os-series#36]
It just gets stuck on this screen whenever I tried to boot on it on my laptop through a USB
![IMG_20210616_182514_246](https://user-images.githubusercontent.com/75160111/122311826-402ad380-ced0-11eb-8184-dee19b3f2d0e.jpg)
If you can't read the text it says
booting double r OS 
warning no console will be available to OS

**Comment by davidcallanan** [comment]
That problem is likely very specific to your hardware.

There is a forum thread talking about this: https://forum.osdev.org/viewtopic.php?f=1&t=28429

Likely reason:

> Your system is using EFI on which GRUB cannot set text mode because the EFI_GRAPHICS_OUTPUT_PROTOCOL doesn't support that.

Not sure if there is anything simple I can change with my code to fix this. I will keep this issue open for now.
