### ISSUE TITLE
Fix readme commands for entering docker environment on linux

### ISSUE THREAD

**Issue by davidcallanan** [davidcallanan/os-series#38]
This resolves issue #1: [no rule to make target](1)

The commands should be the following when entering the docker build environment:

- Linux: `docker run --rm -it -v "$(pwd)":/root/env myos-buildenv`
- MacOS: `docker run --rm -it -v "$(pwd)":/root/env myos-buildenv`
- Windows (CMD): `docker run --rm -it -v "%cd%":/root/env myos-buildenv`
- Windows (PowerShell): `docker run --rm -it -v "${pwd}:/root/env" myos-buildenv`

If you are using git bash, WSL, or msys2 on windows, you'll probably need to use the linux command above.

**Comment by bonelesschickenbone** [comment]
When I put in 'make build-x86_64' it always says 'makefile:5:*** missing separator. Stop.'

**Comment by davidcallanan** [comment]
Changes merged to master.

**Comment by Beatra-sudo** [comment]
It still give me the same error "make *** No rule to make target  'build x86_64' . stop."
