### ISSUE TITLE
set xy funcion

### ISSUE THREAD

**Issue by ajh123** [davidcallanan/os-series#4]
in print.c we can do
```
void print_set_x_y(size_t Lcol , size_t Lrow){
    col = Lcol;
    row = Lrow;
}
```

and in our print.h
```
void print_set_x_y(size_t col , size_t row);
```
Now in kernel main.c
```
    print_set_x_y(10,10);
    print_str("Hello, world?");
```
this will put " Hello, world? " at 10 10

**Comment by davidcallanan** [comment]
That is a nice feature, I'll consider adding it in a future tutorial. However, I'd like to keep the print functions platform-agnostic, and this function wouldn't work consistently with different numbers of rows and columns.
