### ISSUE TITLE
make: *** No rule to make target 'build-x86_64'.  Stop. 

### ISSUE THREAD

**Issue by FlyAvalan** [davidcallanan/os-series#42]
Hey, I am using Windows 11 and this error is unstoppable for me!!! I am trying to fix but can't i used "make build-x86_64"

**Comment by davidcallanan** [comment]
Try the solution here: #38 .

You might need to use a different command when entering the docker environment, before running `make`.

**Comment by FlyAvalan** [comment]
I already tried that and it still doesn't work.

**Comment by FlyAvalan** [comment]
I used everything and nothing 
worked

**Comment by FlyAvalan** [comment]
PS C:\Users\brand\Documents\OS-Avalan> docker run --rm -it -v cd:/root/env avalanos-buildenv
root@79172fe51fae:~/env# make build-x86_64
make: *** No rule to make target 'build-x86_64'.  Stop.
root@79172fe51fae:~/env#

**Comment by davidcallanan** [comment]
@FlyAvalan

> PS C:\Users\brand\Documents\OS-Avalan> docker run --rm -it -v cd:/root/env avalanos-buildenv

This is the wrong command. Please use the command I mentioned above. If the problem is still happening, please screenshot all the commands so I can be 100% sure that you are doing it correctly.

**Comment by FlyAvalan** [comment]
OH I got another error in the windows cmd

**Comment by FlyAvalan** [comment]
makefile:5: *** insufficient number of arguments (2) to function 'patsubst'.  Stop.

**Comment by FlyAvalan** [comment]
So it now found the makefile but this is a problem now

**Comment by FlyAvalan** [comment]
![awreawrawrawr](https://user-images.githubusercontent.com/56940206/126555282-31868abc-105a-4888-9bc9-7059e2376c83.PNG)

**Comment by FlyAvalan** [comment]
> @FlyAvalan
> 
> > PS C:\Users\brand\Documents\OS-Avalan> docker run --rm -it -v cd:/root/env avalanos-buildenv
> 
> This is the wrong command. Please use the command I mentioned above. If the problem is still happening, please screenshot all the commands so I can be 100% sure that you are doing it correctly.

Can you help me with this problem to?

**Comment by davidcallanan** [comment]
> Can you help me with this problem too?

You probably have a typo in your makefile.

**Comment by FlyAvalan** [comment]
> x86_64_asm_source_files := $(shell find src/impl/x86_64 -name *.asm)
> x86_64_asm_object_files := $(patsubst src/impl/x86_64/%.asm, build/x86_64/%.o, $(x86_64_asm_source_files))
> 
> $(x86_64_asm_object_files): build/x86_64/%.o : src/impl/x86_64/%.asm
> mkdir -p $(dir $@) && \
> nasm -f elf64 -o $(patsubst build/x86_64/%.o : src/x86_64/%.asm, $@) -o $@
> 
> .PHONY: build-x86_64
> build-x86_64: $(x86_64_asm_object_files)
> mkdir -p dist/x86_64
> x86_64-elf-ld -n -o dist/x86_64/kernel.bin -T targets/x86_64/linker.ld $(x86_64_asm_object_files)
> cp dist/x86_64/kernel.bin targets/x86_64/iso/boot/kernel.bin && \
> grub-mkrescure /usr/lib/grub/i386-pc -o dist/x86_64/kernel.iso targets/x86_64/iso

This correct?

**Comment by FlyAvalan** [comment]
It's Episode 1!

**Comment by FlyAvalan** [comment]
Omg lol I had typo

**Comment by FlyAvalan** [comment]
But still need to replace it

**Comment by FlyAvalan** [comment]
Lol NOW IT WORKS!!!!!!

**Comment by FlyAvalan** [comment]
It was a typo sorry.
