### ISSUE TITLE
How Do I install QEMU and Docker?

### ISSUE THREAD

**Issue by xLunarr** [davidcallanan/os-series#45]
Im on a linux, so how do I install it? @davidcallanan @davidcallanan @davidcallanan @davidcallanan @
@davidcallanan @davidcallanan @davidcallanan @davidcallanan

Did I just do that? No, it would be very immature. Carry on and answer my darn question.

(and no i didnt just do that)

**Comment by davidcallanan** [comment]
Hey @NotDiamondZ @NotDiamondZ  @NotDiamondZ  @NotDiamondZ @NotDiamondZ @NotDiamondZ @NotDiamondZ @NotDiamondZ 

Docker installation instructions here: https://docs.docker.com/engine/install/

QEMU instructions here: https://www.qemu.org/download/#linux

**Comment by NotDiamondZ** [comment]
OK THANK U

but how do i run them on linux ubuntu

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by davidcallanan** [comment]
Using the commands in your terminal like I show in the video.

**Comment by NotDiamondZ** [comment]
oK

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
