### ISSUE TITLE
Episode 2 - First make

### ISSUE THREAD

**Issue by bckelley** [davidcallanan/os-series#5]
I get this error the first time

root@eb48b894aae2:~/env# make build-x86_64
mkdir -p dist/x86_64 && \
x86_64-elf-ld -n -o dist/x86_64/kernel.bin -T targets/x86_64/linker.ld  build/x86_64/boot/header.o  build/x86_64/boot/main.o  build/x86_64/boot/main64.o && \
cp dist/x86_64/kernel.bin targets/x86_64/iso/boot/kernel.bin && \
grub-mkrescue /usr/lib/grub/i386-pc -o dist/x86_64/kernel.iso targets/x86_64/iso
x86_64-elf-ld: build/x86_64/boot/main.o: in function `start':
src/impl/x86_64/boot/main.asm:(.text+0x2a): relocation truncated to fit: R_X86_64_16 against `.rodata'
Makefile:10: recipe for target 'build-x86_64' failed
make: *** [build-x86_64] Error 1

**Comment by davidcallanan** [comment]
@bckelley I see you closed the issue.

Did you get it fixed? How? Was this a problem on your end, or a bug with my code?
