### ISSUE TITLE
Docker destroy my OS

### ISSUE THREAD

**Issue by Andrej123456789** [davidcallanan/os-series#56]
I need to enter safe mode in Windows 10 and do force delete of Docker Desktop

**Comment by M1sterPl0w** [comment]
This isn't a question related to this series I guess, however, I recommend Linux (Pop!_OS is easy to start with) for using Docker e.g. Windows is terrible at it.

**Comment by Andrej123456789** [comment]
I find new OS DEV tutorial series from Poncho. Lol
Also, Lubuntu is better than PopOS

**Comment by ElectroBoy404NotFound** [comment]
Windows is just trash for cross-platform development, and on that making a os? i dont think so! Same currupted windows os here
