### ISSUE TITLE
Bug in print.c?

### ISSUE THREAD

**Issue by mharleyaz** [davidcallanan/os-series#64]
I think there might be a bug in print.c in the print_newline() function.  Line #48 says: clear_row(NUM_COLS - 1).  I think it should be: clear_row(NUM_ROWS - 1).

I think clearing rows 26-80 might make whatever follows video memory very unhappy. 😁

**Comment by davidcallanan** [comment]
Thank you. I will be fixing this soon.

Duplicate of #3

**Comment by davidcallanan** [comment]
Will be resolved in episode 3.
