### ISSUE TITLE
could not load PC BIOS 'bios-256k.bin'

### ISSUE THREAD

**Issue by sumanta-ghosh** [davidcallanan/os-series#7]
I am getting the below error in my WIn10

_**qemu: could not load PC BIOS 'bios-256k.bin'**_

![image](https://user-images.githubusercontent.com/2699051/108519808-02d28280-72f0-11eb-9303-44ad205d05f1.png)

**Comment by Daxiel1992** [comment]
This is the BIOS file qemu uses. Check the qemu installation folder for the .bin file and when you run the command, add "-L /path/to/bios.bin", without the quotes of course.

**Comment by sumanta-ghosh** [comment]
Thanks @Daxiel1992  , finally able to run using the below command

`qemu-system-x86_64 -L "C:/Program Files/qemu/" -cdrom dist/x86_64/kernel.iso`

**Comment by davidcallanan** [comment]
@sumanta-ghosh Did I find your stackoverflow question? https://stackoverflow.com/questions/66266448/qemu-could-not-load-pc-bios-bios-256k-bin

**Comment by davidcallanan** [comment]
Another potential solution ([this youtube comment thread](https://www.youtube.com/watch?v=wz9CZBeXR6U&lc=UgxxHCjUvqp3kcCnU314AaABAg)).

![image](https://user-images.githubusercontent.com/40340425/126335871-78ae54b6-6ac2-4eb4-a53d-ccddd0ebe29c.png)
