### ISSUE TITLE
When will the next episode be out or is the series over?

### ISSUE THREAD

**Issue by AFellowSpeedrunner** [davidcallanan/os-series#75]
Wanna continue on it but there is not another episode and I've been waiting since August. No rush or anything it's just I wanna know when the next one is expected to release.

**Comment by Madz-miner** [comment]
yeah same
an episode about interrupts and inputs would be awesome

**Comment by Florian-Mahlberg** [comment]
Doubt that anything will get added here ;(

**Comment by AFellowSpeedrunner** [comment]
yeah im giving up hope

**Comment by AFellowSpeedrunner** [comment]
Assuming that this guy has given up on this, closing...
