### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by wolfgangmauer** [davidcallanan/os-series#9]
![grafik](https://user-images.githubusercontent.com/27953724/108608274-3da6ea00-73c6-11eb-9a6c-5ef9380117ce.png)

**Comment by PrestonWebDev** [comment]
what does your Dockerfile look like?

**Comment by wolfgangmauer** [comment]
Cloned the master, no changes yet

**Comment by wolfgangmauer** [comment]
After reinstalling Ubuntu, works as expected
